DROP database IF EXISTS `jpa_JBD`;

CREATE database IF NOT EXISTS `jpa_JBD`;
use `jpa_JBD`;

CREATE TABLE `TEACHER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FNAME` varchar(45) DEFAULT NULL,
  `LNAME` varchar(45) DEFAULT NULL,
  `CONTACT_NO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


INSERT INTO `TEACHER` (`TID`,`TNAME`,`TSUBJECT`,`TDEGREE`) VALUES (1,'JAYANTA','JAVA','MSC PHP');
INSERT INTO `TEACHER` (`TID`,`TNAME`,`TSUBJECT`,`TDEGREE`) VALUES (1,'JAYANTA','JAVA','MSC PHP');

